### ISSUE TITLE
Write access for Owncloud  

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/yunohost.multimedia#1]
How can I give the write access to the multimedia folder in the home/$user/Multimedia
I can only see the media folder in the home folder from owncloud for now.

**Comment by maniackcrudelis** [comment]
Owncloud devrait avoir les droits d'écriture sur le dossier.
Pour le vérifier, tu peux utiliser la commande getfacl sur le dossier.

Mais, dans certains cas, owncloud peut mettre du temps à prendre en comptes ses droits.
Il faut alors forcer la réactualisation de l'arborescence de owncloud.

`sudo -u owncloud php /var/www/owncloud/console.php files:scan --all`

**Comment by anmol26s** [comment]
It works now.
Thanks
