### ISSUE TITLE
Possibilité de créer et un controller un dossier sans source

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/yunohost.multimedia#2]
Salut, j'essaye d'utiliser yunohost.multimedia pour l'app Couchpotato mais il semble manquer l'option dont j'ai besoin.

Je cherche à ajouter un dossier "Movie" dans share/video. Ce dossier movie n'existe que dans yunohost.multimedia, il n'a pas de source liée.
Est-il possible de faire cela avec ynh_media_addfolder.sh ? Je n'ai pas l'impression

Merci

**Comment by maniackcrudelis** [comment]
Salut scith

Tu peux tout à fait créer le dossier Movie dans share/video et ensuite utiliser le script ynh_media_addfolder.sh pour l'intégrer à ton app Couchpotato, si nécessaire.

Tu es libre de créer les dossiers que tu souhaites à l'intérieur des dossiers.

**Comment by scith** [comment]
Ah OK je vois. Donc si je ne veux pas ajouter le dossier à couchpotato, j'ai juste a le créer dans yunohost.multimédia avec mkdir puis setfacl sur le groupe média c'est ça ?

**Comment by maniackcrudelis** [comment]
Euh je regarde, ça fait bien longtemps que j'ai plus touché à ce code...
[...]
Si Couchpotato à juste besoin d'un accès en lecture sur le dossier Movie, en effet tu peux te contenter de le créer et de lui ajouter les droits.
Pour ce faire, tu peux d'ailleurs simplement relancer le script ynh_media_build.sh, il n'écrase rien et il redonne les droits d'accès corrects sur tout les dossiers.

Mais pourquoi tu veux créer un dossier Movie dans Videos si c'est juste pour en lire le contenu? Pourquoi ne pas utiliser Videos directement?

**Comment by scith** [comment]
C'est aussi pour écrire dedans. Parce qu'ensuite Sickrage (sériés TV) aura besoin d'un Vidéo/Sériés. Je peux pas tout mettre dans vidéo sinon les 2 vont se marcher dessus

**Comment by maniackcrudelis** [comment]
Ok, c'était juste pour comprendre, ça n'est pas problématique de toute manière.

Mais du coup c'est lequel qui devra écrire? Sickrage ou couchpotato?
Quoi qu'il en soit, comme indiqué dans le readme, si ton app a besoin d'un droit d'écriture elle doit être ajoutée au groupe multimedia. Ça devrait être suffisant.

**Comment by scith** [comment]
Couchpotato écrit dans share/vidéo/movies et /share/torrent
Sickrage écrit dans share/vidéo/series et /share/torrent

Du coup je vais créer les dossiers a la main, relancer le build pour les droits, et les rajouter dans le groupe multimédia

Merci
