### ISSUE TITLE
Possibilité de donner l'accès en écriture qu'à certains dossiers ?

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/yunohost.multimedia#3]
Salut,
Je ne sais pas si c'est intéressant (et utile), mais est-il possible de donner l'accès en écriture qu'à certains dossiers ? Par exemple juste à share/video ?
Merci

**Comment by maniackcrudelis** [comment]
Je sais pas si c'est nécessaire et utile en effet, car l'intérêt de ce dossier est d'être disponible pour toutes les apps.
Donc ça reviendrais à limiter l'accès en écriture aux autres apps.

Quel est le but?
