### ISSUE TITLE
Pourquoi unzip ?

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/yunohost.multimedia#4]
Salut,
Je me demandais. Y a-t-il un intérêt à télécharger le master.zip puis le dézipper plutôt que git clone ?
Merci

**Comment by maniackcrudelis** [comment]
Non il n'y en a aucun :-)

**Comment by scith** [comment]
En fait le git clone ne fonctionne pas à cause de https://github.com/YunoHost-Apps/yunohost.multimedia/blob/f457daf702d94d2d169b0bb1720129fd094efcaa/script/ynh_media_build.sh#L49
:dancer:

**Comment by maniackcrudelis** [comment]
Spécifie le dossier de destination de ton git clone, ça devrait le faire.
