### ISSUE TITLE
Error on post_user_delete hook execution

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/yunohost.multimedia#7]
On Debian Stretch, I get this when I delete a user:
>Attention : ./50-ynh_media: ligne 6 : [: -n : opérateur binaire attendu

By the way, the hook assigns $1 to $user, but then uses $1 again...

**Comment by Josue-T** [comment]
Hello,

I still have the old version of this code. Probably it come from nextcloud. Is it possible ?

**Comment by maniackcrudelis** [comment]
As this helper isn't yet official, yes it's totally possible that you have an older version.
